# Generated by Django 4.1.6 on 2023-04-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerpaint', '0002_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
