# Generated by Django 4.1.6 on 2023-04-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerpaint', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='lobby_name',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(to='fingerpaint.user'),
        ),
    ]
